=== shrine-maiden-heavy-industries/arcana/contrib/schemas/aracana.target-def.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://raw.githubusercontent.com/shrine-maiden-heavy-industries/arcana/main/contrib/schemas/aracana.target-def.schema.json",
	"title": "Target Definition",
	"description": "Arcana build system target definition file",
	"type": "object",
	"properties": {
		"triple": {
			"type": "string",
			"description": "Target triple"
		},
		"name": {
			"type": "string",
			"description": "Target name"
		},
		"properties": {
			"type": "object",
			"description": "Target properties",

			"properties": {
				"cpu": {
					"type": "object",
					"description": "Target CPU description",

					"properties": {
						"family": {
							"type": "string",
							"description": "Target CPU Family"
						},
						"name": {
							"type": "string",
							"description": "Target CPU name"
						}
					},

					"required": [ "family", "name" ]
				},
				"endian": {
					"type": "string",
					"description": "Target endian",
					"enum": ["little", "big", "middle"]
				},

				"sizes": {
					"type": "object",
					"description": "Target type sizes"
				}
			},

			"required": [ "cpu", "endian", "sizes" ]
		},

		"variables": {
			"type": "object",
			"description": "Arbitrary variable definitions"
		},

		"binaries": {
			"type": "object",
			"description": "Target toolchain binaries"
		},

		"options": {
			"type": "object",
			"description": "Language options for target"
		}
	},

	"required": [
		"triple",
		"name",
		"properties",
		"variables",
		"binaries",
		"options"
	]
}

=== shrine-maiden-heavy-industries/arcana/arcana/targets/defs/embedded/tm4c123gh6pm.json
{
	"$schema": "https://raw.githubusercontent.com/shrine-maiden-heavy-industries/arcana/main/contrib/schemas/aracana.target-def.schema.json",

	"triple": "arm-none-eabi",
	"name": "Tiva-C TM4C123GH6PM",

	"properties": {
		"sizes": {
			"char": 1,
			"short": 2,
			"int": 4,
			"long": 4,
			"longlong": 8,
			"size_t": 4,
			"ptrdiff_t": 4,
			"void*": 4,
			"float": 4,
			"double": 8,
			"longdouble": 8,
			"wchar_t": 2
		},
		"cpu": {
			"family": "arm",
			"name": "cortex-m4f"
		},
		"endian": "little"
	},

	"variables": {
		"COMMON_FLAGS": ["-mthumb", "-mcpu=cortex-m4", "-march=armv7e-m+fp", "-mfpu=fpv4-sp-d16", "-mfloat-abi=softfp"],
		"COMPILER_FLAGS": ["-ffunction-sections", "-fdata-sections", "-DPART_TM4C123GH6PM", "-DARM_MATH_CM4F", "-DTARGET_IS_BLIZZARD_RA1"],
		"LINKER_FLAGS": ["-nostartfiles", "--static", "-Wl,--gc-sections"],
		"PLUGIN_DIR": "nya",
		"AR_ARGS": ["--plugin", "${PLUGIN_DIR}${PATH_SEP}liblto_plugin.so"]
	},

	"binaries": {
		"c": "${triple}-gcc",
		"cxx": "${triple}-g++",
		"ar": ["${triple}-ar", "${AR_ARGS}"],
		"as": "${triple}-as",
		"strip": "${triple}-strip",
		"objcopy": "${triple}-objcopy",
		"objdump": "${triple}-objdump",
		"size": "${triple}-size",
		"gdb": "${triple}-gdb"
	},

	"options": {
		"c": {
			"compile_args": ["${COMMON_FLAGS}", "${COMPILER_FLAGS}"],
			"link_args": ["${COMMON_FLAGS}", "${LINKER_FLAGS}"]
		},
		"cxx": {
			"compile_args": ["${COMMON_FLAGS}", "${COMPILER_FLAGS}", "-fno-rtii", "-fno-exceptions"],
			"link_args": [ "${COMMON_FLAGS}", "${LINKER_FLAGS}" ]
		}
	}
}

=== shrine-maiden-heavy-industries/arcana/arcana/targets/defs/embedded/atxmega256a3u.json
{
	"$schema": "https://raw.githubusercontent.com/shrine-maiden-heavy-industries/arcana/main/contrib/schemas/aracana.target-def.schema.json",

	"triple": "avr",
	"name": "AVR atxmega256a3u",

	"properties": {
		"sizes": {
			"char": 1,
			"short": 2,
			"int": 2,
			"long": 4,
			"longlong": 8,
			"size_t": 2,
			"ptrdiff_t": 2,
			"void*": 2,
			"float": 2,
			"double": 8,
			"longdouble": 8,
			"wchar_t": 2
		},
		"cpu": {
			"family": "avr",
			"name": "avrxmega6"
		},
		"endian": "little"
	},

	"variables": {
		"COMMON_FLAGS": ["-mdouble=64", "-mlong-double=64", "-mmcu=atxmega256a3u", "-ffreestanding"],
		"COMPILER_FLAGS": ["-ffunction-sections", "-fdata-sections"],
		"PLUGIN_DIR": "nya",
		"AR_ARGS": ["--plugin", "${PLUGIN_DIR}${PATH_SEP}liblto_plugin.so"]
	},

	"binaries": {
		"c": "${triple}-gcc",
		"cxx": "${triple}-g++",
		"ar": ["${triple}-ar", "${AR_ARGS}"],
		"as": "${triple}-as",
		"strip": "${triple}-strip",
		"objcopy": "${triple}-objcopy",
		"objdump": "${triple}-objdump",
		"size": "${triple}-size"
	},

	"options": {
		"c": {
			"compile_args": ["${COMMON_FLAGS}", "${COMPILER_FLAGS}"],
			"link_args": ["${COMMON_FLAGS}", "-nostd"]
		},
		"cxx": {
			"compile_args": ["${COMMON_FLAGS}", "${COMPILER_FLAGS}", "-fno-rtii", "-fno-exceptions"],
			"link_args": [ "${COMMON_FLAGS}", "-nostd" ]
		}
	}
}
